In [1]:
import sys
sys.path.append('/Users/shayneufeld/GitHub/mouse_bandit/data_preprocessing_code')
sys.path.append('/Users/shayneufeld/GitHub/mouse_bandit')
import support_functions as sf
import numpy as np
import pandas as pd
import scipy as sp
import bandit_preprocessing as bp
import sys
import os
import behavior_database

## load in database

In [2]:
record_df = pd.read_csv('/Users/shayneufeld/GitHub/mouse_bandit/session_record.csv',index_col=0)

In [3]:
record_df.shape

(793, 16)

## Add single day (multi mice)

In [4]:
DAY = '04072017'
ROOT = '/Users/shayneufeld/Dropbox/Shay_BehaviorFiles/BehaviorData/datesfirst'
root_day = os.path.join(ROOT,DAY)

mouse_folders = os.listdir(root_day)

for mouse in mouse_folders:
    if not mouse[0] == '.':
        curr_dir = os.path.join(root_day,mouse)

        record_df = behavior_database.add_session(curr_dir,record_df)

In [5]:
mouse_folders

['K1', 'K13', 'K7', 'K9', 'Q43', 'Q45']

In [5]:
record_df.tail(10)

,Session ID,Mouse ID,Date,Phase,Left Reward Prob,Right Reward Prob,Block Range Min,Block Range Max,No. Trials,No. Blocks,No. Rewards,p(high Port),Decision Window Duration,Min Inter-trial-interval,Left Solenoid Duration,Right Solenoid Duration
791,04062017_Q43,Q43,2017-04-06 00:00:00,2.0,0.8,0.2,50.0,50.0,496.0,7.0,349.0,0.79,2.0,1.5,35.0,35.0
792,04062017_Q45,Q45,2017-04-06 00:00:00,2.0,0.8,0.2,50.0,50.0,946.0,12.0,641.0,0.80,2.0,1.5,35.0,35.0
793,04072017_K1,K1,2017-04-07 00:00:00,2.0,0.9,0.1,50.0,50.0,541.0,9.0,453.0,0.90,2.0,1.5,35.0,35.0
794,04072017_K10,K10,2017-04-07 00:00:00,1.0,1.0,1.0,1000.0,1000.0,111.0,0.0,111.0,0.00,5.0,1.5,40.0,40.0
795,04072017_K11,K11,2017-04-07 00:00:00,2.0,0.0,1.0,50.0,50.0,292.0,4.0,240.0,0.82,2.0,1.5,35.0,35.0
796,04072017_K13,K13,2017-04-07 00:00:00,2.0,0.9,0.1,50.0,50.0,459.0,7.0,372.0,0.88,2.0,1.5,35.0,35.0
797,04072017_K7,K7,2017-04-07 00:00:00,2.0,0.8,0.2,50.0,50.0,449.0,6.0,319.0,0.77,2.0,1.5,35.0,35.0
798,04072017_K9,K9,2017-04-07 00:00:00,2.0,0.8,0.2,50.0,50.0,299.0,3.0,179.0,0.63,2.0,1.5,35.0,35.0
799,04072017_Q43,Q43,2017-04-07 00:00:00,2.0,0.8,0.2,50.0,50.0,555.0,8.0,406.0,0.87,2.0,1.5,35.0,35.0
800,04072017_Q45,Q45,2017-04-07 00:00:00,2.0,0.8,0.2,50.0,50.0,583.0,7.0,394.0,0.78,2.0,1.5,35.0,35.0

In [8]:
date = '10032016'
date_str = str(date)

pd.to_datetime(date_str,format='%m%d%Y')

Timestamp('2016-10-03 00:00:00')

In [30]:
record_df.loc[659,'Mouse ID'] = 'K9'

In [31]:
record_df[record_df['Mouse ID'] == 'k7']

Empty DataFrame
Columns: [Session ID, Mouse ID, Date, Phase, Left Reward Prob, Right Reward Prob, Block Range Min, Block Range Max, No. Trials, No. Blocks, No. Rewards, p(high Port), Decision Window Duration, Min Inter-trial-interval, Left Solenoid Duration, Right Solenoid Duration]
Index: []

In [6]:
record_df.to_csv(path_or_buf='/Users/shayneufeld/GitHub/mouse_bandit/session_record.csv')

# Need to change dates to actual date objects

- convert all to strings
- check if string is 8 characters long. if its 7, add a 0 at the beginning
- convert to datetime objects

In [7]:
# convert to strings

dates = record_df['Date'].values
dates_str = []
datetimes = []

for date in dates:
    date_str = np.str(date)
    
    if (len(date_str) == 7):
        date_str = '0' + date_str
    
    dates_str.append(date_str)
    
    datetimes.append(pd.to_datetime(date_str,format='%m%d%Y'))

ValueError: time data '2017-03-15 00:00:00' does not match format '%m%d%Y' (match)

In [11]:
len(datetimes)

680

In [29]:
datetimes[0]

Timestamp('2016-11-01 00:00:00')

In [17]:
record_df_copy.iloc[0]['Date']

'11012016'

In [16]:
record_df_copy.loc[:679].shape

(680, 16)

In [20]:
record_df_copy = record_df.copy()
record_df_copy.loc[:679,'Date'] = datetimes;

In [21]:
record_df_copy.head(5)

,Session ID,Mouse ID,Date,Phase,Left Reward Prob,Right Reward Prob,Block Range Min,Block Range Max,No. Trials,No. Blocks,No. Rewards,p(high Port),Decision Window Duration,Min Inter-trial-interval,Left Solenoid Duration,Right Solenoid Duration
0,11012016_K1,K1,2016-11-01 00:00:00,1.0,1.0,1.0,1000.0,1000.0,8.0,0.0,8.0,0.00,10.0,0.5,35.0,35.0
1,11022016_K1,K1,2016-11-02 00:00:00,1.0,1.0,1.0,1000.0,1000.0,85.0,0.0,85.0,0.00,10.0,0.5,35.0,35.0
2,11032016_K1,K1,2016-11-03 00:00:00,1.0,1.0,1.0,1000.0,1000.0,104.0,0.0,104.0,0.00,3.0,1.0,35.0,35.0
3,11042016_K1,K1,2016-11-04 00:00:00,2.0,0.1,0.9,50.0,50.0,70.0,1.0,50.0,0.83,2.0,1.0,35.0,35.0
4,11082016_K1,K1,2016-11-08 00:00:00,1.0,1.0,1.0,500.0,500.0,118.0,0.0,118.0,0.00,5.0,1.0,60.0,60.0

In [22]:
record_df.head(5)

,Session ID,Mouse ID,Date,Phase,Left Reward Prob,Right Reward Prob,Block Range Min,Block Range Max,No. Trials,No. Blocks,No. Rewards,p(high Port),Decision Window Duration,Min Inter-trial-interval,Left Solenoid Duration,Right Solenoid Duration
0,11012016_K1,K1,11012016,1.0,1.0,1.0,1000.0,1000.0,8.0,0.0,8.0,0.00,10.0,0.5,35.0,35.0
1,11022016_K1,K1,11022016,1.0,1.0,1.0,1000.0,1000.0,85.0,0.0,85.0,0.00,10.0,0.5,35.0,35.0
2,11032016_K1,K1,11032016,1.0,1.0,1.0,1000.0,1000.0,104.0,0.0,104.0,0.00,3.0,1.0,35.0,35.0
3,11042016_K1,K1,11042016,2.0,0.1,0.9,50.0,50.0,70.0,1.0,50.0,0.83,2.0,1.0,35.0,35.0
4,11082016_K1,K1,11082016,1.0,1.0,1.0,500.0,500.0,118.0,0.0,118.0,0.00,5.0,1.0,60.0,60.0

In [26]:
record_df = record_df_copy.copy()

In [27]:
record_df.head(20)

,Session ID,Mouse ID,Date,Phase,Left Reward Prob,Right Reward Prob,Block Range Min,Block Range Max,No. Trials,No. Blocks,No. Rewards,p(high Port),Decision Window Duration,Min Inter-trial-interval,Left Solenoid Duration,Right Solenoid Duration
0,11012016_K1,K1,2016-11-01 00:00:00,1.0,1.0,1.0,1000.0,1000.0,8.0,0.0,8.0,0.00,10.0,0.5,35.0,35.0
1,11022016_K1,K1,2016-11-02 00:00:00,1.0,1.0,1.0,1000.0,1000.0,85.0,0.0,85.0,0.00,10.0,0.5,35.0,35.0
2,11032016_K1,K1,2016-11-03 00:00:00,1.0,1.0,1.0,1000.0,1000.0,104.0,0.0,104.0,0.00,3.0,1.0,35.0,35.0
3,11042016_K1,K1,2016-11-04 00:00:00,2.0,0.1,0.9,50.0,50.0,70.0,1.0,50.0,0.83,2.0,1.0,35.0,35.0
4,11082016_K1,K1,2016-11-08 00:00:00,1.0,1.0,1.0,500.0,500.0,118.0,0.0,118.0,0.00,5.0,1.0,60.0,60.0
5,11092016_K1,K1,2016-11-09 00:00:00,1.0,1.0,1.0,500.0,500.0,133.0,0.0,133.0,0.00,5.0,1.0,60.0,60.0
6,11102016_K1,K1,2016-11-10 00:00:00,2.0,0.0,1.0,30.0,30.0,213.0,4.0,134.0,0.63,5.0,1.0,35.0,35.0
7,11112016_K1,K1,2016-11-11 00:00:00,2.0,0.0,1.0,50.0,50.0,315.0,5.0,258.0,0.82,2.0,1.0,35.0,35.0
8,11142016_K1,K1,2016-11-14 00:00:00,2.0,0.1,0.9,50.0,50.0,415.0,5.0,284.0,0.72,2.0,1.0,35.0,35.0
9,11152016_K1,K1,2016-11-15 00:00:00,2.0,0.1,0.9,50.0,50.0,315.0,4.0,228.0,0.77,2.0,1.0,35.0,35.0
10,11162016_K1,K1,2016-11-16 00:00:00,2.0,0.1,0.9,50.0,50.0,217.0,3.0,169.0,0.85,2.0,1.0,35.0,35.0
11,11172016_K1,K1,2016-11-17 00:00:00,2.0,0.2,0.8,30.0,40.0,198.0,3.0,131.0,0.80,2.0,1.0,35.0,35.0
12,11182016_K1,K1,2016-11-18 00:00:00,2.0,0.8,0.2,20.0,40.0,213.0,4.0,128.0,0.65,2.0,1.0,35.0,35.0
13,11212016_K1,K1,2016-11-21 00:00:00,2.0,0.2,0.8,50.0,50.0,349.0,4.0,219.0,0.74,2.0,1.0,35.0,35.0
14,11222016_K1,K1,2016-11-22 00:00:00,2.0,0.8,0.2,20.0,40.0,281.0,6.0,200.0,0.84,2.0,1.0,35.0,35.0
15,11292016_K1,K1,2016-11-29 00:00:00,2.0,0.1,0.9,50.0,50.0,399.0,6.0,305.0,0.82,2.0,1.0,35.0,35.0
16,11302016_K1,K1,2016-11-30 00:00:00,2.0,0.8,0.2,10.0,40.0,470.0,10.0,289.0,0.68,2.0,1.0,35.0,35.0
17,12012016_K1,K1,2016-12-01 00:00:00,2.0,0.2,0.8,50.0,50.0,91.0,1.0,54.0,0.77,2.0,1.0,35.0,35.0
18,12022016_K1,K1,2016-12-02 00:00:00,2.0,0.2,0.8,10.0,40.0,194.0,5.0,127.0,0.75,2.0,1.0,35.0,35.0
19,12052016_K1,K1,2016-12-05 00:00:00,2.0,0.2,0.8,10.0,40.0,364.0,8.0,238.0,0.75,2.0,1.0,35.0,35.0